Create first version of the Sign up
loopstudio/crowdfunding-fe pull request #1
Opened 2022-10-17 15:57 UTC by FacuEM

#### :page_facing_up: Description:

In this PR the first version of the Sign up is created. React-hook-form and yup are used to manage the form and validate the fields. wagmi is used to obtain the address of the user who wants to register.

For the moment only the values obtained from the form + the address are logged until we have the backend ready.

---

#### :play_or_pause_button: Demo:
https://www.loom.com/share/2739b005cb564f198af83a0ad0c90234

2022-10-17 17:59 UTC, renacargnelutti commented on pages/signup/index.js
> +        <Label htmlFor="nameInput">Name:</Label>
On the backend side, I added the username field instead of the name
We can talk about that later on today

2022-10-18 13:26 UTC, FacuEM commented
TODO: display errors

2022-10-19 17:16 UTC, RodriCabrera requested changes

2022-10-19 17:16 UTC, RodriCabrera commented on pages/signup/index.js
> +    name: string().required(),
I think it should be `username` instead of `name` to be able to have `isValid = true`. 
If not, I'm getting `isValid =  false`

2022-10-27 20:33 UTC, RodriCabrera approved these changes

2022-12-04 20:52 UTC, marcosmartinez7 approved these changes
LGTM

2023-02-07 15:17 UTC, closed without merging